### ISSUE TITLE
Lot's of warnings in shell

### ISSUE THREAD

**Issue by kirrg001** [gemfury/cli#4]
Hi!

Using the CLI for the first time. Getting lot's of warnings on every cmd.

> Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
/Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/file_part.rb:53: warning: constant ::UploadIO is deprecated
/Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/file_part.rb:59: warning: constant ::UploadIO is deprecated
/Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/file_part.rb:61: warning: constant ::Parts is deprecated

How to get rid of these warnings? Thanks

osx 12.2 apple m1

**Comment by rykov** [comment]
This issue is with an older version of the [old CLI](/gemfury/gemfury). We recommend [switching to this new CLI](https://gemfury.com/guide/cli/), or upgrading to version `0.13.0+` of the old one to remove the warnings.
