### ISSUE TITLE
Package ID required instead of the name

### ISSUE THREAD

**Issue by rauno56** [gemfury/cli#5]
v0.21.0 doesn't let me delete packages by the name.

Only the ID(like "pkg_1AN30j") works but
1. nowhere is it documented;
3. there's no easy way to acquire the ID through the CLI - listing packages only reports the name.

Currently need to get the ID from the URLs on the web dashboard.

**Comment by rykov** [comment]
@rauno56 We had a bug where CLI failed silently if the account had more than one result for a delete query. For example, having multiple packages with the same name, but of a different kind. We've now fixed the issue in CLI v0.22.0 to support deleting all matching packages (with confirmation).

Furthermore, if you'd like to narrow down to one specific package, you can add a kind-specifier prefix to the name `KIND:NAME` as described in the *Naming conflicts* section here: https://gemfury.com/guide/cli/basic-usage/
